openapi: 3.0.1
info:
  title: list-files
  description: service that lists files from NFS or S3
  version: 1.0.0
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

paths:
  /listFiles/NFS/{modelPath}:
    get:
      operationId: getFromNFS
      tags:
        - NFS
      summary: gets the files
      parameters:
        - $ref: '#/components/parameters/modelPath'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/content'
  /listFiles/S3/{modelPath}:
    get:
      operationId: getFromS3
      tags:
        - S3
      summary: gets the files
      parameters:
        - $ref: '#/components/parameters/modelPath'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/content'
    post:
      operationId: postFromS3ToS3
      tags:
        - S3
      summary: gets the files
      parameters:
        - $ref: '#/components/parameters/modelPath'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/content'

components:
  parameters:
    modelPath:
      in: path
      name: modelPath
      required: true
      schema:
        type: string
      description: The 3d model name
  schemas:
    error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
    content:
      type: array
